/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CalculatorComponent: typeof import('./components/CalculatorComponent.vue')['default']
    CurrencyComponent: typeof import('./components/CurrencyComponent.vue')['default']
    HomeComponent: typeof import('./components/HomeComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
